
applications:
  - name: task-node-application
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/EdgarEktibaryan/task-node-app.git
      targetRevision: refs/heads/main
      path: env/argo-app
      directory:
        recurse: false
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
    info:
    - name: url
      value: https://github.com/EdgarEktibaryan/task-node-app.git